name: Test

on:
  push:
    branches: [ "pu" ]
  pull_request:
    branches: [ "pu" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, macos-latest] # for now we drop windows
        os: [ubuntu-latest, macos-latest, windows-latest]
        perl-version: ['5.38', '5.40']
        
    runs-on: ${{ matrix.os }}
    name: Perl ${{ matrix.perl-version }} on ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev 
          sudo apt-get install -y libasound2-dev \
                                  libx11-dev \
                                  libxrandr-dev \
                                  libxi-dev \
                                  libgl1-mesa-dev \
                                  libglu1-mesa-dev \
                                  libxcursor-dev \
                                  libxinerama-dev \
                                  libwayland-dev \
                                  libxkbcommon-dev

      - name: Build and Test
        uses: perl-actions/install-with-cpanm@v1.7
        with:
          install: .
          local-lib: "./local"
          tests: true
          verbose: true
     
